[package]
name = "planchette"
version = "0.1.0"
edition.workspace = true
include.workspace = true
rust-version.workspace = true

[dependencies]
axum = "0.8.1"
seance = { path = "../seance" }
serde.workspace = true
tokio = { version = "1.44.1", features = ["full"] }

[lints]
workspace = true
